services:
  frontend:
    image: nginx:alpine
    container_name: ironclad_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    container_name: ironclad_gateway
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/ironclad?replicaSet=rs0
    depends_on:
      - service_inventario
      - service_auth
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    image: mongo:7
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
  
  service_auth:
    build: ./service_auth
    container_name: service_auth
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/ironclad?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  
  service_inventario:
    build: ./service_inventario
    container_name: service_inventario
    ports:
      - "3002:3002"
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/ironclad?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: