tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "outline": "#75777e",
                        "secondary": "#545e76",
                        "on-error": "#ffffff",
                        "on-secondary-fixed-variant": "#3c475d",
                        "outline-variant": "#c5c6cd",
                        "tertiary-fixed": "#ffdbcb",
                        "tertiary-fixed-dim": "#ffb692",
                        "surface-container-lowest": "#ffffff",
                        "on-primary": "#ffffff",
                        "surface": "#f8f9ff",
                        "error": "#ba1a1a",
                        "tertiary-container": "#341100",
                        "on-primary-fixed-variant": "#3a475f",
                        "on-error-container": "#93000a",
                        "on-surface": "#191c20",
                        "inverse-primary": "#bac7e4",
                        "on-secondary-container": "#5a647c",
                        "inverse-surface": "#2e3135",
                        "on-primary-fixed": "#0e1c32",
                        "surface-variant": "#e1e2e8",
                        "on-tertiary-fixed": "#341100",
                        "primary-fixed": "#d7e3ff",
                        "secondary-container": "#d7e2ff",
                        "on-primary-container": "#77849f",
                        "on-tertiary": "#ffffff",
                        "surface-container-highest": "#e1e2e8",
                        "on-surface-variant": "#44474d",
                        "surface-container-high": "#e7e8ee",
                        "tertiary": "#000000",
                        "background": "#f8f9ff",
                        "on-background": "#191c20",
                        "secondary-fixed": "#d7e2ff",
                        "error-container": "#ffdad6",
                        "on-tertiary-fixed-variant": "#7a3000",
                        "surface-container": "#eceef3",
                        "primary-fixed-dim": "#bac7e4",
                        "primary": "#000000",
                        "surface-dim": "#d8dae0",
                        "surface-container-low": "#f2f3f9",
                        "surface-tint": "#525f78",
                        "on-secondary-fixed": "#101b30",
                        "secondary-fixed-dim": "#bbc6e2",
                        "inverse-on-surface": "#eff0f6",
                        "on-secondary": "#ffffff",
                        "primary-container": "#0e1c32",
                        "surface-bright": "#f8f9ff",
                        "on-tertiary-container": "#dc5d00"
                    },
                    "borderRadius": {
                        "DEFAULT": "1rem",
                        "lg": "2rem",
                        "xl": "3rem",
                        "full": "9999px"
                    },
                    "fontFamily": {
                        "headline": ["Manrope"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    }
                },
            },
        }